name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4.2.0
      - name: Setup Java
        uses: actions/setup-java@v4.4.0
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build the Kotlin project
        run: mvn -B clean install
        working-directory: kotlin
      - name: Upload the coverage report to Codecov
        uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
