name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    env:
      MAVEN_ARGS: -B --color always
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v5.0.0
      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build the Kotlin project
        run: mvn clean install
        working-directory: kotlin
      - name: Upload the coverage report to Codecov
        uses: codecov/codecov-action@v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
