name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  build-kotlin:
    name: Build Kotlin
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v3.4.1
        with:
          distribution: temurin
          java-version: 11
      - name: Cache the Maven local repository
        uses: actions/cache@v3.0.6
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-
      - name: Build the project
        run: mvn -B clean install
        working-directory: kotlin
      - name: Upload the coverage report to Codecov
        uses: codecov/codecov-action@v3.1.0
