name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Build the Kotlin project
        run: mvn -B clean install
        working-directory: kotlin
      - name: Upload the coverage report to Codecov
        uses: codecov/codecov-action@v3.1.5
